import React, { useState, useEffect } from 'react';
import { View, Text, TextInput, Button, Alert } from 'react-native';
import { useAuth } from '../auth/Authcontext';
import axios from 'axios';

import  {API_URL} from '../config';

const TwoFactorSetupScreen = ({ navigation }) => {
  const { userToken, verifyOTP } = useAuth();
  const [loading, setLoading] = useState(true);
  const [otp, setOtp] = useState('');

  // --- 1. Fetch 2FA Setup Details ---
  useEffect(() => {
    const fetch2FASetup = async () => {
      try {
          await axios.post(`${API_URL}/send-otp`, {}, {
          headers: { 
            Authorization: `Bearer ${userToken}`,
            'Content-Type': 'application/json' 
          },
          
        });
        
      } catch (error) {
        Alert.alert('Error', 'Failed to load 2FA setup details.');
        navigation.goBack(); 
      } finally {
        setLoading(false);
      }
    };

    fetch2FASetup();
  }, []);

  // --- 2. Verify the 6-Digit Code ---
  const handleVerify2FA = async () => {
    setLoading(true);
    try {
      const response = await verifyOTP(otp)
      if(!response.success) {
        Alert.alert('Verification Failed', response?.data?.message || 'Invalid code. Please try again.');
        
      }
      if(response.success) {
        navigation.navigate('Dashboard');
      }
    } catch (error) {
      Alert.alert('Verification Failed', error?.data?.message || 'Invalid code. Please try again.');
      navigation.navigate('Login');
    } finally {
      setLoading(false);
    }
  };

  return (
    <View style={{ flex: 1,
      padding: 20,
      justifyContent: 'center'}}>
      <Text style={{ fontSize: 16,
    marginBottom: 15,
    textAlign: 'center',
    color: '#333',}}>
        Enter the 6-digit code generated by the app below to verify.
      </Text>

      <TextInput
        style={{height: 50,
          borderColor: '#ccc',
          borderWidth: 1,
          marginBottom: 15,
          paddingHorizontal: 10,
          borderRadius: 5,textAlign: 'center',}}
        placeholder="6-Digit Code"
        value={otp}
        onChangeText={setOtp}
        keyboardType="numeric"
        maxLength={6}
        autoCapitalize="none"
      />
      
      <Button 
        title={loading ? "Verifying..." : "Verify and Enable 2FA"} 
        onPress={handleVerify2FA} 
        disabled={loading || otp.length !== 6} 
      />
    </View>
  );
};



export default TwoFactorSetupScreen;